apiVersion: v1
kind: Service
metadata:
  name: service2-message-app
  labels:
    app: service2-message-app
spec:
  ports:
    - name: http 
      port: 80
      targetPort: 5000
  selector:
    app: service2-message-app
  type: ClusterIP
