apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: traffic-generator
  namespace: hemhal-dev
spec:
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
        - image: <IMAGE_NAME_HERE>
          env:
            - name: TARGET_URL
              value: "http://<service1-route-url>"
  traffic:
    - latestRevision: true
      percent: 100
